export type ReleaseStatus = 'stable'

export interface PlatformRelease {
  version: string
  date: string
  status: ReleaseStatus
  title: string
  summary: string
  highlights: string[]
  metrics: string[]
  assetName: string
  guidedInstall: boolean
  upgradeNotice?: {
    title: string
    summary: string
    guidePath: string
    action: string
  }
}

export const repositoryUrl = 'https://github.com/xiaoxiao113213/agents-platform'
export const officialSiteUrl = 'https://mmmqaz.cn'

export const releases: PlatformRelease[] = [
  {
    version: 'v1.0.34',
    date: '2026-08-23',
    status: 'stable',
    title: '协作空间与 Agent 扩展能力闭环升级',
    summary: '事项、资料、MCP 与 Skill 形成可追踪闭环，自定义 MCP 和后台任务边界让 Agent 协作更完整可靠。',
    highlights: [
      'Issue 产品概念统一为协作空间，事项处理、用户澄清、资料沉淀和 AI 直接关闭使用一致语言。',
      '协作空间资料支持多级目录和立即生效，长文档可以完整滚动阅读。',
      '协作空间 MCP 与处理 Skill 支持版本识别、自动同步和手动重复同步。',
      '自定义 MCP 支持 stdio 与 HTTP，完整覆盖新增、编辑、启停、同步、密钥保护和删除。',
      'Agent 列表增加我的与他人共享快速筛选，并明确标识个人主 Agent。',
      '独立版本历史以非研发语言完整展示每次迭代的功能、升级和验收说明。',
      '后台子 Agent 的重复长轮询会自动限时或降级，降低长任务停滞风险。',
      '本版本不新增域名、DNS、证书、公开端口或生产配置键，并修复了已知问题。',
    ],
    metrics: ['AI 直接关闭闭环', 'MCP/Skill 自动同步', '自定义 MCP 全生命周期'],
    assetName: 'devops-v1.0.34-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后复验协作能力与资料目录',
      summary: '先导入本版本运行环境并完成累计升级，再验证一个协作空间绑定、一个二级资料目录和一个自定义 MCP。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.33',
    date: '2026-08-23',
    status: 'stable',
    title: 'Project 首页品牌展示优化',
    summary: '自定义 Logo 在 Project 首页按自身尺寸和原始比例展示，横向与小尺寸品牌标识不再被压进固定方框。',
    highlights: [
      'Project 首页 Logo 使用图片固有尺寸与原始宽高比，不再强制占满固定正方形槽位。',
      '横向、纵向和小尺寸 Logo 都保持清晰自然的品牌比例。',
      '超大 Logo 会在响应式边界内等比缩小，标题和项目创建区域不会被撑开或遮挡。',
      '登录页、侧边栏和主题预览等固定 Logo 槽位保持原有稳定布局。',
      '完整继承 v1.0.32 的项目协作、Agent 共享、大型工作区、角色多主题、模型切换和项目应用能力。',
      '本版本不新增域名、DNS、证书、公开端口、生产配置键或外部服务要求，并修复了已知问题。',
    ],
    metrics: ['Logo 原始比例', '固有尺寸展示', '响应式安全边界'],
    assetName: 'devops-v1.0.33-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后检查 Project 首页 Logo',
      summary: '先导入本版本运行环境并完成累计升级，再以一个横向 Logo 和一个小尺寸 Logo 检查 Project 首页展示比例。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.32',
    date: '2026-08-23',
    status: 'stable',
    title: '项目协作、共享与应用网关可靠性升级',
    summary: '最近项目、Agent 共享、协作资料和大型工作区更加清晰；模型切换与项目应用 JSON 请求在失败和长连接场景下保持可靠。',
    highlights: [
      '最近项目按真实会话活动排序并增加到 10 个，非默认项目完成对话后会及时回到列表前方。',
      'Agent 支持直接重命名和进入完整管理页，项目卡片明确展示所属 Agent 及其运行状态。',
      '项目协作统一展示 AI 待审事项和资料，资料文件支持由 Agent 创建、替换与重命名。',
      'Agent 共享可以选择全部项目或指定项目，并可独立决定成员是否允许创建新项目。',
      '工作区文件树改为逐层按需加载，大型目录不再因为一次性数量上限而缺失后续文件。',
      '角色可以绑定多个界面主题，多角色成员继续按实际角色与主题组合切换。',
      '对话模型报错后可以直接切换模型继续发送，不再需要刷新页面才能使用新模型。',
      '项目应用完整支持 JSON POST、上传、流式响应与 WebSocket，不再需要修改请求类型绕过平台网关。',
      '两套 Web 界面的 Logo、主题背景、工具栏位置和单 Agent 布局同步完善。',
      '本版本不新增域名、DNS、证书、公开端口或外部服务要求，并修复了已知问题。',
    ],
    metrics: ['10 个最近项目', '项目级 Agent 共享', '大型目录按需加载'],
    assetName: 'devops-v1.0.32-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后复验共享范围与项目应用',
      summary: '先导入本版本运行环境并完成累计升级，再检查一个共享 Agent、一个大型工作区和一个包含 JSON POST 的项目应用。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.31',
    date: '2026-08-23',
    status: 'stable',
    title: '登录、主题与项目协作体验完善',
    summary: '全站统一登录与角色主题正式生效，对话、项目、Skill、MCP、应用和 Agent 配额形成更清晰可靠的日常工作体验。',
    highlights: [
      '平台首页、能力广场、Agent、项目、会话和系统管理统一在登录后使用，原目标地址会在登录后继续打开。',
      '新增主题管理与角色主题选择，内置默认、律所、工业制造、编程研发等可编辑主题，多角色成员可以切换并保留偏好。',
      '对话思考过程保持稳定，后台会话完成后会提醒并可直接查看结果；会话菜单和输入区同步精简。',
      '最近项目支持搜索、显示所属 Agent 并恢复真实工作区，导航、对话列表和工具栏的折叠状态会跨项目保持。',
      '所有 Agent 默认具备 skill-creator 与 find-skills，文件产物收集和远程 Agent 提交更加可靠。',
      '达到 Agent 创建上限后不再显示创建入口，服务端仍会执行配额校验并返回明确提示。',
      '项目服务统一以“应用”呈现，project 界面的 MCP 页面直接展示实例、Server、项目、Agent 与同步状态。',
      '最高权限账号不再依赖固定账号编号，普通账号和角色维护页面也无法误改该系统属性。',
      '两套登录页与主题编辑页完成视觉和响应式优化，并修复了已知问题。',
    ],
    metrics: ['8 套可编辑主题', '跨会话完成提醒', 'MCP 实例直达'],
    assetName: 'devops-v1.0.31-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后确认角色主题与工作区',
      summary: '先导入本版本运行环境，再完成累计升级；登录后切换一次角色主题，并打开最近项目、MCP 和一个历史会话确认数据保持。',
      guidePath: '/deploy#update',
      action: '查看升级步骤',
    },
  },
  {
    version: 'v1.0.30',
    date: '2026-08-22',
    status: 'stable',
    title: '项目式界面与双 Web 交付',
    summary: '新增以项目为中心的第二套平台界面，经典功能完整保留；默认 Agent 与真实项目入口形成稳定工作路径，部署时可选择并随时切换界面。',
    highlights: [
      '项目式首页、最近项目和项目列表直接连接真实 Agent 项目与原工作区深链。',
      '每位用户的第一个有效 Agent 成为不可删除、不可转移的默认 Agent，新用户自动补齐。',
      '经典界面的 Agent、Skill、MCP、Issue、系统管理和工作区能力在项目式界面中完整保留。',
      'Linux 包同时携带 classic 与 project 两套 Web，支持安装时选择、升级保留和运行中安全切换。',
      '数据库设计与数据库专用 Agent 退役，历史 Agent 项目、会话、工作区和产物记录继续保留。',
      '本版本不新增 DNS、证书、公开端口或后端配置键，并修复了已知问题。',
    ],
    metrics: ['双 Web 可切换', '默认 Agent 长期绑定', '真实项目直达'],
    assetName: 'devops-v1.0.30-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后合并 Web 入口并选择界面',
      summary: '保留现场域名与证书，只把 Nginx 静态根目录合并到 web/current，再用 web status/use 验证两套界面。',
      guidePath: '/deploy#web-mode',
      action: '查看双 Web 升级步骤',
    },
  },
  {
    version: 'v1.0.29',
    date: '2026-08-21',
    status: 'stable',
    title: '工作区文件更清晰，交付产物更可靠',
    summary: '大型依赖目录不再挤占文件列表；默认和自定义忽略规则可按项目维护，Windows 与 Linux 产物路径统一识别。',
    highlights: [
      '常见语言与框架的依赖目录、缓存和构建中间文件默认隐藏，让源码与交付文件优先显示。',
      '默认规则可以逐项停用和恢复，自定义忽略目录支持新增、修改、删除与目录行快捷操作。',
      '文件树与搜索共享同一配置，保存后立即生效，交付目录默认保持可见。',
      'Windows 与 Linux 项目产物按当前项目边界统一识别，减少文件存在但平台无法固化的情况。',
      '升级不新增域名、Nginx、证书、端口或外部服务要求，并修复了已知问题。',
    ],
    metrics: ['12 类默认规则', '项目级自定义忽略', '跨平台产物路径'],
    assetName: 'devops-v1.0.29-linux-x64.tar.gz',
    guidedInstall: true,
  },
  {
    version: 'v1.0.28',
    date: '2026-08-21',
    status: 'stable',
    title: 'Agent 持续对话与企业运维可观测性升级',
    summary: '对话追加、长任务续行和历史浏览更加稳定；全局看板补齐主机与 Agent 资源数值、趋势和 Top 10，并提供安全的环境变量管理。',
    highlights: [
      '运行中的新输入显示在输入框上方并按顺序执行，不再打断当前任务或混入消息历史。',
      '长任务在工具调用、后台任务和阶段性进度后继续运行，直到形成最终结果、明确失败或确实需要用户决策。',
      '加载更早消息时保持当前阅读位置，快速切换和刷新会话时丢弃过期响应，减少消息跳动和错位。',
      '最后一条运行中消息恢复明确的处理中状态，并在真实终态到达后可靠释放。',
      '全局运维看板展示 CPU、内存、磁盘和网络的具体数值、七天趋势及 Top 10，用户 Agent 资源可直接定位。',
      'Agent 磁盘统计限定为自身工作区真实占用，兼容 Docker 与 Ubuntu 主机，不再显示整台物理机磁盘容量。',
      '资源采集使用低频、错峰和有界任务，避免监控工作挤占对话、项目服务和平台请求。',
      'Agent 工作台新增环境变量入口，普通变量可编辑，密钥变量只显示配置状态且不会回显明文。',
      '文件型对话产物可固化到平台并继续下载，Agent 文件后续移动或下线不再直接导致历史产物失效。',
      'API Key 可按模型维护计价属性，全局用量看板据此展示可核对的成本估算。',
      '本版本不新增域名、DNS、Nginx、证书或公开端口配置要求，现场配置继续完整保留。',
      'JDK、Maven、pnpm 软件内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['输入顺序执行', '资源七天趋势', 'Agent 工作区真实磁盘'],
    assetName: 'devops-v1.0.28-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后复验连续对话与运维指标',
      summary: '等待 Agent 重新连接后连续追加两条输入，并在全局看板核对一个 Agent 的具体资源数值与七天趋势。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.27',
    date: '2026-08-19',
    status: 'stable',
    title: '项目服务动态端点与精确 Token 看板升级',
    summary: '项目服务复用 Agent 当前工程中的唯一进程并自动记录服务事实；全局看板可按用户、API Key 和实际模型核对精确 Token。',
    highlights: [
      '项目服务的本地入口与平台公开入口统一指向 Agent 当前工程中的同一个服务进程。',
      '应用监听端口、公开域名、网关入口和挂载路径均取自当前运行环境，不再依赖示例或历史值。',
      '同一服务只保留一个受管进程，更新、启停和重启不会额外启动第二份应用。',
      '发布成功后自动记录服务目录、生命周期入口、当前端点和公开地址，后续对话可以延续正确状态。',
      '执行新的服务动作前会重新读取当前平台状态，历史记录中的端口和地址不会被当作固定配置。',
      '全局看板分别统计非缓存输入、缓存创建、缓存读取和输出 Token，并展示实际模型与容量属性。',
      '支持自定义日期、按天或按周聚合，以及用户、API Key、模型、来源和统计精度组合筛选。',
      '当前筛选结果可导出 CSV，历史兼容数据与新版本精确数据会明确区分。',
      '本版本不新增域名、DNS、Nginx、证书或公开端口配置要求，现场配置继续完整保留。',
      'JDK、Maven、pnpm 软件内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['单服务单进程', '动态端点', '精确 Token 可核对'],
    assetName: 'devops-v1.0.27-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后复验项目服务与 Token 看板',
      summary: '等待 Agent 重新连接后，确认项目服务的两个入口访问同一实例，并用一次真实对话核对 Token 明细。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.26',
    date: '2026-08-19',
    status: 'stable',
    title: '项目资料目录与 Agent 协作升级',
    summary: '项目资料支持多级文件夹和完整 Agent 索引，对话排版、用户筛选与全局看板同步提升可读性和真实性。',
    highlights: [
      '项目资料支持多级文件夹、移动、重命名和空目录删除。',
      'Agent 可先读取完整资料索引，再按目录读取已发布文档、链接或文件。',
      '对话保留 Markdown 原始软换行、标题、列表和代码结构，阅读密度更适中。',
      '工作台移除不常用入口，并减少对话运行期间的无关刷新。',
      '最高管理员用户筛选保留账号名称，不再回显数字 ID。',
      '用户趋势使用真实消息和活动数据，Agent 离线时明确显示连接问题。',
      'Linux 升级预检失败时可靠释放生命周期锁，修正后可直接重试。',
      'JDK、Maven、pnpm 软件内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['多级资料目录', 'Agent 完整资料索引', '真实使用趋势'],
    assetName: 'devops-v1.0.26-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后复验资料索引与老会话',
      summary: '等待 Agent 重新连接后，检查一个多级资料目录、Agent 索引和包含标题列表代码的已有会话。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.25',
    date: '2026-08-18',
    status: 'stable',
    title: 'Agent 长回复阅读密度优化',
    summary: '对话正文、标题和列表改为更紧凑的排版节奏，在一个屏幕内展示更多有效信息，同时保留代码与表格的清晰边界。',
    highlights: [
      'Agent 对话正文行高与段落间距收紧，长篇中文回复可以连续阅读更多内容。',
      '标题、普通列表、嵌套列表和列表项分别控制间距，结构清楚且不再出现大片空白。',
      'Markdown 源码中的结构换行不再被重复放大为额外空白行。',
      '代码块、引用、表格、公式和图表继续保留独立间距，紧凑排版不会挤压技术内容。',
      '调整只作用于 Agent 消息正文，不影响工具调用、审批卡片、输入区和消息边界。',
      'JDK、Maven、pnpm 软件内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['长回复更紧凑', '列表层级更清楚', '技术内容边界保留'],
    assetName: 'devops-v1.0.25-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后刷新并检查一个长会话',
      summary: '重新打开一个包含标题、列表、代码块和表格的已有会话，确认页面已加载新版本并保持清晰紧凑。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.24',
    date: '2026-08-18',
    status: 'stable',
    title: '长会话、远程同步与窗口并发稳定性升级',
    summary: '长会话恢复、Windows 项目服务、远程 Agent 重连和单窗口子 Agent 并发形成完整稳定性闭环。',
    highlights: [
      '长会话自动压缩并在必要时使用有界上下文继续，完整历史、地址和会话名称保持不变。',
      '异常空回复明确重试和报错，不再显示成功或额外创建新对话。',
      '每个对话默认最多同时运行两个子 Agent，更多任务分批等待，不同对话互不占用名额。',
      '远程 Agent 重复同步和平台重启时及时清理旧连接，降低连接与句柄累积风险。',
      'Windows Runtime 升级兼容受限 PowerShell 5.1，不再依赖可选哈希命令。',
      'Windows 项目服务生命周期不再因后台服务继承输出而等待两分钟。',
      '项目服务继续使用统一脚本、稳定端口和完整启停删除闭环。',
      'JDK、Maven、pnpm 软件内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['单会话并发有界', '长会话连续恢复', 'Windows 生命周期快速返回'],
    assetName: 'devops-v1.0.24-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后复验老会话与项目服务',
      summary: '等待 Agent 重新连接后，继续一个老会话，并在 Windows 与 Linux Agent 上各复验一个项目服务生命周期。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.23',
    date: '2026-08-18',
    status: 'stable',
    title: '多会话、长任务与项目服务稳定性升级',
    summary: '新对话、长时间 Workflow、项目服务生命周期和 Agent Key 权限形成完整闭环，页面升级后可自动刷新。',
    highlights: [
      '新对话在首条消息后正式建立，并发创建、运行和切换时不再串消息、运行状态或 Workflow 状态。',
      '长时间 Workflow、Task 和子 Agent 保持控制连接，超过十分钟仍可持续回传并正常结束。',
      '项目服务按当前操作系统使用统一脚本，支持单服务创建、更新、日志、启停、重启和卸载。',
      '端口、PID、进程树和健康路径统一核验，删除后确认释放端口，资源不足时主动给出配置建议。',
      'Agent Key 始终按所有者权限过滤，转移时自动收缩 Key、会话和自动任务。',
      '页面检测到服务器新版本后自动刷新；最高管理员可按用户筛选 Agent。',
      '对话附件支持 500 MiB，Maven 继续使用阿里云依赖和插件镜像。',
      'JDK、Maven、pnpm 软件内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['并发会话隔离', '长任务持续回传', '单服务生命周期闭环'],
    assetName: 'devops-v1.0.23-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后复验长任务与项目服务',
      summary: '等待 Agent 重新连接后，分别运行真实长任务和项目服务启停，确认进度、端口、健康与日志正常。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.22',
    date: '2026-08-17',
    status: 'stable',
    title: '项目服务资源诊断与嵌入兼容升级',
    summary: '项目服务在启动前主动评估资源，旧项目自动同步最新能力，同时完善 Maven 国内镜像和平台内嵌验收。',
    highlights: [
      '项目服务启动、构建和重启前后主动检查 CPU、内存、已有服务负载及构建峰值，高风险时给出最低和推荐配置。',
      '启动失败会识别 OOM、SIGKILL 和退出码 137，停止无意义重试，并明确资源差额和可执行的降载建议。',
      '已启用项目服务能力的旧项目会按内容指纹自动同步最新 Skill，无需重新创建项目或手工重装。',
      'Maven 离线安装默认配置阿里云公共镜像，已有 Maven 可直接修复 settings，无需重复传输软件包。',
      '项目服务增加 iframe、响应头、CSP、Cookie、HTTPS 和登录跳转验收规则，避免浏览器直接打开正常但平台内无法使用。',
      'JDK、Maven、pnpm 软件内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['资源风险主动提醒', '旧项目能力自动刷新', '平台嵌入完整验收'],
    assetName: 'devops-v1.0.22-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后复验项目服务与 Maven 配置',
      summary: '等待 Agent 重新连接并同步项目能力，随后在平台内打开真实服务，检查登录、接口和资源提示。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.21',
    date: '2026-08-17',
    status: 'stable',
    title: 'Agent 实例隔离与管理看板全面加固',
    summary: '解决单个 Agent 重建后遗留实例抢占连接的问题，并完善运维诊断、用户数据、返回状态和工程 Skill。',
    highlights: [
      'Docker Agent 识别当前运行实例，遗留实例不能再抢占控制连接或项目服务通道。',
      '运维看板显示当前与遗留容器，最高管理员可在严格校验后精确清理遗留实例。',
      '用户数据看板增加活跃、在线、资源密度、使用分层、趋势、搜索、筛选和业务列排序。',
      '从对话工作区返回管理台时恢复原页签、管理员用户筛选、搜索和远程状态。',
      '项目服务面板优化长文本换行，服务、端点、端口和状态在常用宽度下更清晰。',
      '内置工程 Skill 增加 SQLite 开发模式和切换 MySQL 时的备份、迁移、校验与回滚流程。',
      'JDK、Maven、pnpm 内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['实例身份隔离', '遗留容器可治理', '管理状态可恢复'],
    assetName: 'devops-v1.0.21-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后确认 Agent 当前实例与运行环境',
      summary: '完成平台升级后等待 Agent 重新连接，在运维看板核对当前实例，再复验真实对话和项目服务。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.20',
    date: '2026-08-16',
    status: 'stable',
    title: '多项目服务、端口与 Agent 重置全面加固',
    summary: '统一管理每个 Agent 的项目服务端口，修复项目应用 JSON、平台重启恢复和单服务故障扩散，并提供管理员安全重置能力。',
    highlights: [
      '同一 Agent 的多个项目、多个服务和多个端点统一分配稳定端口，启动前检测占用，停止后保留，删除后释放。',
      '项目应用 JSON 不再被平台代理追加额外内容，上传、接口、SSE 和 WebSocket 继续使用公开项目域名。',
      '平台重启后主 Agent 会快速重新连接并立即唤醒项目服务通道，缩短服务不可访问窗口。',
      '单个服务构建或启动失败只标记该服务，其他项目和服务继续同步与运行。',
      '最高管理员可重置异常 Agent 的运行环境、SDK 和会话状态，同时保留所有项目目录与聊天上传文件。',
      '全局看板展示 Agent 端口、服务端点、冲突、未声明监听和离线状态，便于快速定位卡顿位置。',
      'JDK、Maven、pnpm 内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['端口稳定分配', '项目服务故障隔离', '重启快速恢复'],
    assetName: 'devops-v1.0.20-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后检查端口登记与项目服务恢复',
      summary: '导入本版本运行环境并完成平台升级后，确认 Agent Runtime 已更新，再打开真实项目服务并检查端口与异常诊断。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.19',
    date: '2026-08-16',
    status: 'stable',
    title: '对话恢复、项目服务和产物提示更稳定',
    summary: '修复浏览器断开后会话长期占用、草稿与正式会话控制不一致、项目服务重复构建以及失效产物只显示通用错误的问题。',
    highlights: [
      '浏览器刷新、断网或关闭页面后，平台会及时取消上游任务并释放会话，不再长期提示上一条消息仍在处理中。',
      '草稿会话切换为正式会话后，停止、恢复、状态查询和继续发送始终控制同一个运行任务。',
      '项目服务恢复相同版本时只重启进程，不再周期性重复构建并覆盖正在使用的产物。',
      '文件型产物被删除或改名时会显示原路径和明确的失效状态，避免用户反复点击无效下载。',
      'JDK、Maven、pnpm 内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['断流及时释放', '同版本恢复不重构建', '失效产物可诊断'],
    assetName: 'devops-v1.0.19-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后确认 Agent Runtime 已更新',
      summary: '导入本版本运行环境并完成平台升级后，确认 Agent 重新连接，再复验老会话、项目服务和文件型产物。',
      guidePath: '/deploy#verify',
      action: '查看升级验证步骤',
    },
  },
  {
    version: 'v1.0.18',
    date: '2026-08-16',
    status: 'stable',
    title: '对话、下载与项目服务长连接全面加固',
    summary: '修复对话状态闪动、大文件下载中断和项目服务长时间运行不稳定，并完善工作区能力管理、定时任务串行和管理员诊断。',
    highlights: [
      '对话前台与后台任务使用统一运行状态，后台工作未结束时不再提前收尾或刷新整页。',
      '文件、产物和远程工作区采用流式分片传输、完整性校验和有界流控，大文件下载更加稳定。',
      '项目服务 HTTP、SSE、WebSocket、上传和下载具备多通道隔离、背压、长连接保活和重启恢复。',
      'Skill 与 MCP 统一在当前 Agent 工作区管理，并可查看当前项目已有 Skill。',
      '定时对话从上一次完成后计算固定间隔，同一会话严格串行，避免重复并发执行。',
      '管理员可按用户查看 Agent、项目服务、节点与隧道的真实状态，离线 Agent 不再显示正常。',
      'JDK、Maven、pnpm 内容没有变化，继续复用 v1.0.15 软件离线包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['对话状态稳定', '大文件流式传输', '项目服务故障隔离'],
    assetName: 'devops-v1.0.18-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级后必须合并项目服务 Nginx 参数',
      summary: '升级器会保留现场 Nginx；请从新模板合并 WebSocket 分流、上游连接复用、长连接超时、请求标识和下载非缓冲路由。',
      guidePath: '/deploy#project-app',
      action: '查看配置与验收步骤',
    },
  },
  {
    version: 'v1.0.17',
    date: '2026-08-15',
    status: 'stable',
    title: 'Skill 导入贡献与项目服务恢复更加稳定',
    summary: '提升 GitHub Skill 包、大型项目 Skill 贡献和旧运行环境项目服务恢复的兼容性，并确保新项目自动具备统一目录规范。',
    highlights: [
      'GitHub 下载的 Skill ZIP 可保留安全的点目录和点文件，不再因常见仓库结构误判导入失败。',
      '大型项目 Skill 贡献改用受控文件传输，降低长时间等待后返回 503 的概率，并在失败后清理临时文件。',
      '每个新建项目和新 Agent 的默认项目都会自动写入项目目录规范 Skill，无需用户重复安装。',
      '旧运行环境不支持新恢复接口时，平台会使用兼容动作重新部署或停止项目服务。',
      'Agent 停止、重启、重建或迁移后会及时断开旧连接，避免请求继续命中过期运行环境。',
      'JDK、Maven、pnpm 内容没有变化，不重复提供软件离线包，继续复用 v1.0.15 软件包和服务器缓存。',
      '修复了已知问题。',
    ],
    metrics: ['GitHub Skill 兼容', '大型贡献稳定', '旧服务自动恢复'],
    assetName: 'devops-v1.0.17-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级前先导入运行环境',
      summary: '先导入本版本运行环境包，再执行平台累计升级；现场配置、项目工作区、会话和已有 Skill 会继续保留。',
      guidePath: '/deploy#update',
      action: '查看升级步骤',
    },
  },
  {
    version: 'v1.0.16',
    date: '2026-08-14',
    status: 'stable',
    title: '项目服务长期运行更稳定，异常可直接定位',
    summary: '修复项目服务运行一段时间后访问超时和网络流量持续升高的问题，并在全局看板提供逐 Agent、逐服务诊断。',
    highlights: [
      '单个项目服务响应过快或浏览器处理过慢时，只中止受影响的访问，不再拖累同一 Agent 的其他服务。',
      '项目服务长时间运行、Agent 断线重连和平台重启后的连接与资源释放更加完整。',
      '全局看板新增项目服务总数、异常数，以及每个 Agent 的服务健康汇总。',
      '逐服务诊断展示 Agent 与通道在线状态、活动请求、连接、数据积压、健康时间和明确问题原因。',
      'Linux 升级预检兼容不同语言环境，不再输出配置键排序告警。',
      '对话稳定、会话恢复、Linux 终端、离线安装和项目服务重建恢复继续纳入统一回归。',
      'JDK、Maven、pnpm 内容没有变化，不重复提供软件离线包，已有环境继续复用缓存。',
      '修复了已知问题。',
    ],
    metrics: ['长时间运行稳定', '单服务故障隔离', '全局诊断可见'],
    assetName: 'devops-v1.0.16-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级前先导入运行环境',
      summary: '先导入本版本运行环境包，再执行平台累计升级；现场配置、项目工作区和会话数据会继续保留。',
      guidePath: '/deploy#update',
      action: '查看升级步骤',
    },
  },
  {
    version: 'v1.0.15',
    date: '2026-08-14',
    status: 'stable',
    title: '项目服务重启和重建后可自动恢复',
    summary: '修复项目服务在平台重启、Agent 重启或容器重建后仍显示运行中但实际无法打开的问题。',
    highlights: [
      '容器重建后即使本地服务状态记录丢失，也会从平台保存的完整配置重新建立运行状态。',
      '打开项目服务前会确认真实运行状态，过期的端口和进程信息不再直接用于访问。',
      '项目服务首访和后台巡检共用同一恢复流程，避免重复启动和持续失败重试。',
      '项目服务响应超时会正确标记为上游服务故障，后续访问可以触发恢复。',
      '保留失败次数和退避保护，故障项目不会形成无限重启循环。',
      '修复了已知问题。',
    ],
    metrics: ['重建后自动恢复', '首访实时确认', '失败状态可追踪'],
    assetName: 'devops-v1.0.15-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级前先导入运行环境',
      summary: '先导入本版本运行环境包，再执行平台累计升级；现场配置、项目工作区和会话数据会继续保留。',
      guidePath: '/deploy#update',
      action: '查看升级步骤',
    },
  },
  {
    version: 'v1.0.14',
    date: '2026-08-14',
    status: 'stable',
    title: 'Agent 重启恢复与持续对话更加稳定',
    summary: '系统或 Agent 重启后会主动恢复项目服务和会话状态，对话页面保持稳定，离线软件安装也更加可靠。',
    highlights: [
      '平台和 Agent 重启后会主动恢复原来要求运行的项目服务，无需先打开服务面板触发恢复。',
      '项目服务恢复过程具备并发保护和失败隔离，单个服务异常不会拖垮整个 Agent 运行进程。',
      'Agent 对话页的后台刷新保持现有对象和界面状态，减少整页闪动、滚动跳动和无关服务刷新。',
      '关闭审核面板后停止无意义的高频审核请求，降低长时间对话的页面负担。',
      '历史会话恢复失败时保留原会话，不会静默创建缺少上下文的新会话。',
      '离线安装命令兼容非交互终端，JDK、Maven 和 pnpm 继续直接复用服务器缓存。',
      'Linux 终端输入、新会话创建、服务入口自动出现和终端角色权限继续保持可用。',
      '修复了已知问题。',
    ],
    metrics: ['重启后自动恢复', '对话界面稳定', '离线安装可靠'],
    assetName: 'devops-v1.0.14-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级前先导入运行环境',
      summary: '先导入本版本运行环境包，再执行平台累计升级；现场配置、项目工作区和会话数据会继续保留。',
      guidePath: '/deploy#update',
      action: '查看升级步骤',
    },
  },
  {
    version: 'v1.0.13',
    date: '2026-08-14',
    status: 'stable',
    title: 'Agent 对话、终端和离线安装恢复稳定',
    summary: '对话不再整页闪动，回合结束后可以可靠继续发送；Linux Docker Agent 终端输入和离线软件安装也已修复。',
    highlights: [
      'Agent 对话执行期间保持当前页面和消息稳定，不再按秒刷新整个对话界面。',
      '上一回合真正结束后才开放下一次发送，避免错误提示上一条消息仍在处理中。',
      '新会话执行期间保持同一会话上下文，不再因地址切换出现跳动或消息抖动。',
      'Linux Docker Agent 终端恢复键盘输入、交互命令和窗口尺寸同步。',
      'Docker Agent 安装离线 JDK、Maven 和 pnpm 时直接复用服务器缓存，减少不必要的传输等待。',
      'Windows 与 Linux 远程 Agent 的原有终端和软件安装方式保持兼容。',
      '修复了已知问题。',
    ],
    metrics: ['对话稳定可续发', 'Linux 终端可输入', '离线安装更快'],
    assetName: 'devops-v1.0.13-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级前先导入运行环境',
      summary: '先导入本版本运行环境包，再执行平台累计升级；需要离线安装 JDK、Maven 或 pnpm 时，继续复用服务器缓存目录。',
      guidePath: '/deploy#update',
      action: '查看升级步骤',
    },
  },
  {
    version: 'v1.0.12',
    date: '2026-08-13',
    status: 'stable',
    title: '项目协作与 Agent 工作区更加完整',
    summary: '项目资料、附件预览、会话恢复、服务入口和终端权限形成更稳定的项目协作闭环。',
    highlights: [
      'Issue 项目新增资料目录、审核发布、历史版本和事项关联，AI 可以读取背景并沉淀确认后的结论。',
      '对话附件支持常用文本、代码、Markdown、图片、PDF 和音视频站内预览。',
      '新建会话立即出现在左侧，快速重复操作只创建一个会话，刷新后不会丢失或重复。',
      'Agent 开发出新的项目服务后，当前项目的服务入口会在对话过程中自动出现，无需刷新页面。',
      '角色管理新增 Agent 终端权限，授权成员可以在其有权访问的 Agent 项目中使用终端。',
      '项目文件按交付类型规范放置，已有工程保持原结构，迁移前必须先得到用户确认。',
      '新建或重建 Agent 的最低配置统一为 2 核、2048 MB。',
      'JDK、Maven 和 pnpm 可从服务器离线缓存安装，避免每个 Agent 重复下载。',
      '视频 Agent 增加成熟镜头制作库，强化产品演示、空间运镜、节奏和声音设计。',
      'Agent 重建跟随当前固定运行环境，停机 Agent 不再沿用历史版本。',
      '修复了已知问题。',
    ],
    metrics: ['会话即时可用', '服务入口自动出现', '终端按角色授权'],
    assetName: 'devops-v1.0.12-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级前先准备运行环境',
      summary: '升级前先导入本版本运行环境包；需要为 Agent 安装 JDK、Maven 或 pnpm 时，再把离线软件包一次解压到默认缓存目录。现场配置和项目数据会继续保留。',
      guidePath: '/deploy#update',
      action: '查看升级步骤',
    },
  },
  {
    version: 'v1.0.11',
    date: '2026-08-13',
    status: 'stable',
    title: '共享对话与刷新恢复更加可靠',
    summary: '多人共用会话时保持顺序，执行中刷新可恢复完整状态，Windows 与 Linux 远程 Agent 的项目能力也更加稳定。',
    highlights: [
      '同一共享会话按顺序处理输入，发送后立即显示执行状态，快速重复点击只产生一次请求。',
      '新会话执行期间刷新会恢复真实会话、工具过程和最终回复，不再残留临时会话。',
      'Windows 与 Linux 远程 Agent 使用各自的平台身份和工作区，同机多个 Agent 相互独立。',
      '项目应用兼容常见端口变量写法，修改配置或人工重启后会重新进行健康检查。',
      '项目应用可按项目开放公网访问，未开放时继续只允许项目成员访问。',
      '项目 Skill 可以贡献到能力广场，贡献者可以继续更新自己分享的版本。',
      'Skill ZIP 导入兼容单个 Markdown 文件和常见 macOS 压缩包元数据。',
      '可以独立导入完整运行环境交付包，再执行平台升级。',
      '修复了已知问题。',
    ],
    metrics: ['共享输入有序', '项目应用可分享', 'Skill 可沉淀'],
    assetName: 'devops-v1.0.11-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级前先检查现场配置',
      summary: 'v1.0.11 没有新增生产配置；项目应用仍需完成通配 DNS 与 Nginx 项目应用虚拟主机配置。',
      guidePath: '/deploy#project-app',
      action: '查看项目应用配置',
    },
  },
  {
    version: 'v1.0.10',
    date: '2026-08-12',
    status: 'stable',
    title: '共享会话与远程 Agent 更加稳定',
    summary: '长任务消息、工具过程和最终回复保持一致，Windows 与 Linux 远程 Agent 的升级、终端和项目能力同步也更加可靠。',
    highlights: [
      '消息、任务进度、工具结果和最终回复保持稳定顺序，刷新后可以恢复完整历史。',
      '错误、停止与中断结果更加清晰，已完成历史不再重复显示实时消息。',
      'API Key 和模型只在当前会话执行期间锁定，其他空闲会话不受影响。',
      'Windows 与 Linux 远程 Agent 统一提供生命周期、升级、状态和日志命令，并展示 Runtime 版本状态。',
      '远程终端输入、输出与断线重连更加稳定，重启时确保只保留一个有效进程。',
      '重建内置 Agent 会保留项目内容，远程项目的项目应用、Skill 和 MCP 同步更加可靠。',
    ],
    metrics: ['共享消息一致', '远程运行稳定', '项目内容保留'],
    assetName: 'devops-v1.0.10-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: '升级前先检查现场配置',
      summary: 'v1.0.10 没有新增生产配置；项目应用仍需完成通配 DNS 与 Nginx 项目应用虚拟主机配置。',
      guidePath: '/deploy#project-app',
      action: '查看项目应用配置',
    },
  },
  {
    version: 'v1.0.9',
    date: '2026-08-11',
    status: 'stable',
    title: '让每个 Agent 项目真正运行完整应用',
    summary: '前端、Java、Node.js、Python 和前后端一体项目都可以在项目空间中运行、自检，并通过独立地址访问。',
    highlights: [
      '每个项目都可以按需添加项目应用能力，统一管理启动、停止、重启、状态和访问入口。',
      '项目应用使用独立子域名访问，静态网站和动态服务保持一致，项目之间相互隔离。',
      '对话中可以直接搜索和添加工程 Skill，不同项目可以自由组合自己的能力。',
      '新增常用前端、Java、Node.js、Python 和一体化工程 Skill，数据库升级随服务启动自动完成。',
      '从旧版本升级后需合并项目应用 Nginx 虚拟主机，并配置项目根域的通配 DNS；版本页提供完整步骤和验证命令。',
      '服务启动会检查端口与进程状态，安装配置更清晰，并修复了已知问题。',
    ],
    metrics: ['完整项目运行', '独立应用地址', '升级配置清单'],
    assetName: 'devops-v1.0.9-linux-x64.tar.gz',
    guidedInstall: true,
    upgradeNotice: {
      title: 'v1.0.9 项目应用升级必做',
      summary: '从旧版本升级后，需要配置项目应用根域与通配 DNS，并将新的项目应用虚拟主机合并到现场 Nginx 配置。',
      guidePath: '/deploy#project-app',
      action: '查看域名与 Nginx 步骤',
    },
  },
  {
    version: 'v1.0.8',
    date: '2026-08-11',
    status: 'stable',
    title: '大型会话更快，任务与产物更稳定',
    summary: '大型会话按需加载历史，多人共享时消息与最终状态保持一致，任务进度和产物展示也更加可靠。',
    highlights: [
      '大型会话优先加载最近消息，需要时可继续查看更早内容，重新进入对话更加顺畅。',
      '多人共用 Agent 和会话时，正在生成的消息、最终回复与刷新后的状态保持一致。',
      '已结束任务不再错误显示为运行中，长计划默认展示摘要并可完整展开阅读。',
      '会话产物打开更快，手工刷新仍可重新校准，无效或空白产物不再占据列表。',
      '减少重复后台请求，并修复了已知问题。',
    ],
    metrics: ['历史按需加载', '共享消息一致', '任务状态准确'],
    assetName: 'devops-v1.0.8-linux-x64.tar.gz',
    guidedInstall: true,
  },
  {
    version: 'v1.0.7',
    date: '2026-08-10',
    status: 'stable',
    title: '项目切换更自然，团队权限更细致',
    summary: '模型连接与 Issue 能力可以按角色分配，运行中的 Agent 支持跨项目查看，长任务消息展示也更加稳定。',
    highlights: [
      '模型连接管理与 Issue 管理统一通过角色权限分配，团队职责不再受固定账号限制。',
      'Issue 权限覆盖查看、项目管理、创建、编辑、评论、流转、删除与项目令牌，操作和数据范围可分别控制。',
      'Agent 执行期间可以切换项目，原任务继续完成，当前页面只显示所选项目的数据和状态。',
      '切回原项目后可继续处理任务问答，项目浏览不会打断正在执行的工作。',
      'Task、子任务和超长内容在分栏和小尺寸窗口中保持稳定，并修复了已知问题。',
    ],
    metrics: ['角色化能力权限', '运行中项目切换', '长内容稳定展示'],
    assetName: 'devops-v1.0.7-linux-x64.tar.gz',
    guidedInstall: true,
  },
  {
    version: 'v1.0.6',
    date: '2026-08-10',
    status: 'stable',
    title: '模型用量清晰可见，共享对话更加稳定',
    summary: '模型连接支持按成员授权并提供多维用量分析，多人共享会话和长任务上下文处理也更加稳定。',
    highlights: [
      '模型连接可以全局共享或只授权给指定成员，团队复用与使用边界都能按需设置。',
      '用量分析按连接、成员和模型展示请求次数及 Token 消耗，并支持日期与对象筛选。',
      '删除模型连接前可以查看关联内容，并先批量替换到其他连接，减少 Agent 使用中断。',
      '多人共用同一 Agent 和会话时，消息顺序、任务过程与最终结果保持一致。',
      '长任务会更早整理上下文并继续执行，同时修复了已知问题。',
    ],
    metrics: ['成员级连接权限', '多维 Token 用量', '共享会话稳定'],
    assetName: 'devops-v1.0.6-linux-x64.tar.gz',
    guidedInstall: true,
  },
  {
    version: 'v1.0.5',
    date: '2026-08-10',
    status: 'stable',
    title: '团队模型连接与远程 Agent 更易使用',
    summary: '团队可以更灵活地复用已配置的模型连接，远程 Agent 支持多模型连接，并进一步减少累计升级后的磁盘占用。',
    highlights: [
      '已启用的模型连接可以在团队 Agent 中直接选择和切换，集中配置后无需每位成员重复录入。',
      '创建远程 Agent 时可以一次绑定多个模型连接、指定默认项，并根据可用模型完成选择。',
      '模型连接的日常维护仍由具备管理权限的成员负责，Agent 使用与连接维护各自保持清晰。',
      '累计升级完成后会清理没有被任何 Agent 使用的旧版本运行环境；仍在使用的内容会自动保留。',
      '安装与升级说明统一到当前累计升级规则，并修复了已知问题。',
    ],
    metrics: ['团队连接共享', '远程 Agent 多模型', '升级自动整理'],
    assetName: 'devops-v1.0.5-linux-x64.tar.gz',
    guidedInstall: true,
  },
  {
    version: 'v1.0.4',
    date: '2026-08-10',
    status: 'stable',
    title: '共享对话稳定性与更灵活的模型接入',
    summary: '多人共享 Agent 的消息与任务过程更加稳定，并加入开箱即用的模型服务、可修改的 Grafana 配置和更清晰的升级进度。',
    highlights: [
      '共享会话按顺序处理每轮对话，消息、任务进度、工具结果和最终回复在所有使用者之间保持一致。',
      '内置 DeepSeek 与 Kimi 模型服务，只需填写 API Key 即可选择平台维护的模型与配置，同时保留完整的自定义接入能力。',
      'Grafana Agent 创建后可修改服务地址、令牌、默认文件夹和多数据源绑定，运行中的 Agent 保存后自动应用。',
      '大型 Office 类 Skill 可以从能力目录完整同步，Agent 管理、小屏布局和站点视觉细节同步优化。',
      '镜像准备与在线升级持续展示进度并支持断点续传，跨版本累计升级更加省心。',
    ],
    metrics: ['共享会话稳定', '内置模型服务', '可恢复升级'],
    assetName: 'devops-v1.0.4-linux-x64.tar.gz',
    guidedInstall: true,
  },
  {
    version: 'v1.0.3',
    date: '2026-08-09',
    status: 'stable',
    title: '多数据源看板与更稳定的 Agent 交付',
    summary: '内置 Agent 的项目规则、能力配置和交付验证更加完整，并支持在一套 Grafana 配置中组合多个数据源。',
    highlights: [
      '一套 Grafana 配置可绑定 1 至 20 套数据源组合，每个 UID 对应一套 MySQL 只读连接，同一大盘的不同组件可分别选用或复用数据源。',
      '内置 Agent 会按各自工作类型稳定初始化规则、Skill、能力配置和项目模板，并在交付前完成自我验证。',
      'Agent 项目网站可从常见构建目录和项目子目录稳定发布，并返回可直接访问的入口。',
      '问答、执行确认和文件工作台的信息更清晰，长内容、权限范围和操作结果更容易阅读。',
      '支持从更早正式版本直接累计升级，并修复了已知问题。',
    ],
    metrics: ['Grafana 多数据源', '内置 Agent 自验证', '累计升级'],
    assetName: 'devops-v1.0.3-linux-x64.tar.gz',
    guidedInstall: true,
  },
  {
    version: 'v1.0.2',
    date: '2026-08-09',
    status: 'stable',
    title: '更省心的安装与项目网站发布',
    summary: '减少重复配置和安装阻断，让平台、Agent 项目网站与运行环境按一致的默认规则协同工作。',
    highlights: [
      'Agent 项目网站自动使用平台当前域名和端口下的固定路径，无需重复填写公开访问地址。',
      '项目网站发布目录跟随平台数据根目录，应用与 Nginx 默认配置保持一致。',
      '安装和启动会直接复用本机已有运行环境，缺少的内容会在需要时自动下载。',
      '部署检查兼容常见 Nginx 配置写法，远程 Agent 地址仅在实际使用该能力时配置。',
      '发布成功后会直接返回可点击的网站入口，并修复了已知问题。',
    ],
    metrics: ['同域项目网站', '更少安装配置', '累计升级'],
    assetName: 'devops-v1.0.2-linux-x64.tar.gz',
    guidedInstall: true,
  },
  {
    version: 'v1.0.1',
    date: '2026-08-08',
    status: 'stable',
    title: '团队权限、项目访问与交付安全完善',
    summary: 'Agent、远程运行环境和 Skill 工作台的权限边界更加清晰，项目应用访问与正式交付也更加可靠。',
    highlights: [
      '本地 Agent、远程 Agent 和 Skill 工作台可以分别按角色授权，成员只会看到自己有权使用的能力。',
      '超级管理员继续拥有完整管理能力，已有 Agent 用户升级后会平滑继承必要权限。',
      '项目应用支持直接打开原始服务地址，并在站内预览不兼容时给出清晰提示。',
      '平台与 Agent 发布的网站统一使用同一域名和端口，项目入口更容易配置和访问。',
      '运行过程中的提问、确认和错误信息统一使用产品语言，减少不必要的底层概念。',
      '安装包不再携带开发源码，正式交付内容和运行所需文件边界更加明确。',
      '修复了已知问题。',
    ],
    metrics: ['角色权限细分', '项目访问清晰', '交付内容收敛'],
    assetName: 'devops-v1.0.1-linux-x64.tar.gz',
    guidedInstall: true,
  },
  {
    version: 'v1.0.0',
    date: '2026-08-08',
    status: 'stable',
    title: 'Agent 工作平台全新版本',
    summary: '以 Agent 项目为核心重构平台入口，统一团队协作、会话、文件、任务、能力与系统管理体验。',
    highlights: [
      'Agent 成为平台主入口，系统管理按角色权限集中到统一管理入口。',
      '团队成员可以共享同一个 Agent，并共同使用会话、项目文件、任务和产物。',
      '项目内置事项协作空间，支持权限分配、事项维护、评论附件、状态记录、需求澄清和处理锁定。',
      '定时任务支持一次、每天、每周、每月和固定间隔执行，并可在执行前检查待处理事项。',
      'Skill 工作台支持上传、分享、删除和同步，Agent 项目可以直接安装所需能力。',
      '项目服务支持新窗口、弹窗和对话区并排打开，并适配不同尺寸的页面布局。',
      '模型连接支持多选绑定和会话内切换，对话支持上下文整理、会话命名和用量信息。',
      '内置通用、数据库、网站、协作空间、Grafana、PPT 和视频等多类 Agent，并支持远程 Agent。',
      '修复了项目切换、共享数据、流式消息、文件预览、项目服务和远程运行中的已知问题。',
    ],
    metrics: ['Agent 项目主入口', '团队共享协作', '多类内置能力'],
    assetName: 'devops-v1.0.0-linux-x64.tar.gz',
    guidedInstall: true,
  },
]

export const latestRelease = releases[0]

export function getReleaseDownloadUrl(release: PlatformRelease) {
  return `${officialSiteUrl}/releases/${release.assetName}`
}

export function getReleasePageUrl(version: string) {
  return `${repositoryUrl}/releases/tag/${version}`
}
